import lumen.gl as gl

# Generated by pugtk's Python shader DSL (pugtk/_glsl_dsl.py) from:
#
#   @vertex_shader
#   def vs(aPos: vec3) -> vec4:
#       return vec4(aPos, 1.0)
#
#   @fragment_shader
#   def fs() -> vec4:
#       base_color: vec3 = Uniform("base_color")
#       return vec4(base_color, 1.0)
#
# asmpython compiles this program itself, so the transpile step (which
# uses CPython's `ast`/`inspect` modules) runs separately, ahead of time,
# to produce the GLSL text below -- see _glsl_dsl.py's module docstring.
vs_src = "#version 330 core\nlayout(location = 0) in vec3 aPos;\nvoid main() {\n    gl_Position = vec4(aPos, 1.0);\n}"
fs_src = "#version 330 core\nout vec4 fragColor;\nuniform vec3 base_color;\nvoid main() {\n    fragColor = vec4(base_color, 1.0);\n}"

win: int = gl.create_gl_window("pugtk GL triangle", 640, 480)
ctx: int = gl.create_context(win)

glfns = gl_import()


@glfns.imported
def glShaderSource() -> int:
    return 0


@glfns.imported
def glCreateShader(shader_type: int) -> int:
    return 0


@glfns.imported
def glCompileShader(shader: int) -> int:
    return 0


@glfns.imported
def glGetShaderiv(shader: int, pname: int, params: list) -> int:
    return 0


@glfns.imported
def glCreateProgram() -> int:
    return 0


@glfns.imported
def glAttachShader(program: int, shader: int) -> int:
    return 0


@glfns.imported
def glLinkProgram(program: int) -> int:
    return 0


@glfns.imported
def glGetProgramiv(program: int, pname: int, params: list) -> int:
    return 0


@glfns.imported
def glDeleteShader(shader: int) -> int:
    return 0


@glfns.imported
def glUseProgram(program: int) -> int:
    return 0


@glfns.imported
def glGenVertexArrays(n: int, arrays: list) -> int:
    return 0


@glfns.imported
def glBindVertexArray(array: int) -> int:
    return 0


@glfns.imported
def glGenBuffers(n: int, buffers: list) -> int:
    return 0


@glfns.imported
def glBindBuffer(target: int, buffer: int) -> int:
    return 0


@glfns.imported
def glBufferData(target: int, size: int, data: list, usage: int) -> int:
    return 0


@glfns.imported
def glVertexAttribPointer(index: int, size: int, ty: int, normalized: int, stride: int, offset: int) -> int:
    return 0


@glfns.imported
def glEnableVertexAttribArray(index: int) -> int:
    return 0


@glfns.imported
def glGetUniformLocation(program: int, name: str) -> int:
    return 0


@glfns.imported
def glUniform3f(location: int, x: float, y: float, z: float) -> int:
    return 0


@glfns.imported
def glClearColor(r: float, g: float, b: float, a: float) -> int:
    return 0


@glfns.imported
def glClear(mask: int) -> int:
    return 0


@glfns.imported
def glViewport(x: int, y: int, w: int, h: int) -> int:
    return 0


@glfns.imported
def glDrawArrays(mode: int, first: int, count: int) -> int:
    return 0


@glfns.imported
def glGetError() -> int:
    return 0


def check(label: str):
    e: int = int(glfns.glGetError())
    print(label)
    print(e)


# ---- Compile + link the shader program -----------------------------------

shader_source_ptr: int = gl_resolve(glfns, "glShaderSource")

vs_id: int = int(glfns.glCreateShader(gl.VERTEX_SHADER))
gl.shader_source(shader_source_ptr, vs_id, vs_src)
glfns.glCompileShader(vs_id)
vs_status: list = [0]
glfns.glGetShaderiv(vs_id, gl.COMPILE_STATUS, vs_status)
print("vertex compile status:")
print(vs_status[0])

fs_id: int = int(glfns.glCreateShader(gl.FRAGMENT_SHADER))
gl.shader_source(shader_source_ptr, fs_id, fs_src)
glfns.glCompileShader(fs_id)
fs_status: list = [0]
glfns.glGetShaderiv(fs_id, gl.COMPILE_STATUS, fs_status)
print("fragment compile status:")
print(fs_status[0])

program: int = int(glfns.glCreateProgram())
glfns.glAttachShader(program, vs_id)
glfns.glAttachShader(program, fs_id)
glfns.glLinkProgram(program)
link_status: list = [0]
glfns.glGetProgramiv(program, gl.LINK_STATUS, link_status)
print("link status:")
print(link_status[0])

glfns.glDeleteShader(vs_id)
glfns.glDeleteShader(fs_id)

# ---- Upload triangle vertex data -------------------------------------------
# list[float] stores raw 8-byte doubles (asmpython's only float width), so
# the vertex attribute below is declared GL_DOUBLE/stride 24 (3 doubles),
# not the usual GL_FLOAT/stride 12 a C program would use for `float[]` data.
vertices: list = [
    0.0, 0.5, 0.0,
    -0.5, -0.5, 0.0,
    0.5, -0.5, 0.0,
]

vao: list = [0]
glfns.glGenVertexArrays(1, vao)
glfns.glBindVertexArray(vao[0])

vbo: list = [0]
glfns.glGenBuffers(1, vbo)
glfns.glBindBuffer(gl.ARRAY_BUFFER, vbo[0])
glfns.glBufferData(gl.ARRAY_BUFFER, len(vertices) * 8, vertices, gl.STATIC_DRAW)

glfns.glVertexAttribPointer(0, 3, gl.DOUBLE, 0, 24, 0)
glfns.glEnableVertexAttribArray(0)

check("after buffer setup")

color_loc: int = int(glfns.glGetUniformLocation(program, "base_color"))
print("base_color uniform location:")
print(color_loc)

glfns.glViewport(0, 0, 640, 480)
glfns.glClearColor(0.05, 0.05, 0.08, 1.0)

# ---- Draw one frame and present --------------------------------------------
glfns.glClear(gl.COLOR_BUFFER_BIT)
glfns.glUseProgram(program)
glfns.glUniform3f(color_loc, 1.0, 0.55, 0.1)
glfns.glBindVertexArray(vao[0])
glfns.glDrawArrays(gl.TRIANGLES, 0, 3)

check("after draw")

gl.swap_window(win)

import _gui_sdl
_gui_sdl.delay(3000)

gl.destroy(win, ctx)
