"""A minimal, purpose-built JSON scanner for glTF documents.

Not a general JSON library -- asmpython has no tagged-union/`Any` value
type, so there's no clean way to represent "parse anything, then branch
on what you got" the way CPython's json.loads() does. glTF's JSON shape
is fixed and known ahead of time (a handful of top-level arrays:
accessors/bufferViews/meshes/buffers/nodes/scenes, each containing
objects with a small set of int/float/str/bool fields), so this scans
directly for the specific fields _gltf_loader.py needs, keyed by their
enclosing array index, instead of building a generic tree first and
walking it second.

The scanning strategy: find each top-level array by name (`"accessors":
[`), then walk its bracket-balanced object entries one at a time,
extracting named int/float/string fields from each with simple text
scans (no real lexer/recursive-descent grammar -- glTF's own JSON is
machine-generated by exporters, never hand-written/irregularly
formatted, so this doesn't need to handle whitespace-in-weird-places or
comments the way a general-purpose JSON parser would).
"""
from __future__ import annotations


def _find_key_array_start(text: str, key: str) -> int:
    """Returns the index of the `[` starting the array value of `"key":`,
    or -1 if the key isn't present at the top level. Doesn't validate
    nesting depth (glTF documents don't repeat top-level key names inside
    nested objects in a way that would create ambiguity for the specific
    keys this loader looks for -- "accessors"/"bufferViews"/"meshes"/
    "buffers" are themselves always top-level array names)."""
    needle: str = "\"" + key + "\""
    idx: int = text.find(needle)
    if idx < 0:
        return -1
    i: int = idx + len(needle)
    n: int = len(text)
    while i < n and text[i] != ":":
        i = i + 1
    i = i + 1
    while i < n and (text[i] == " " or text[i] == "\n" or text[i] == "\t" or text[i] == "\r"):
        i = i + 1
    if i >= n or text[i] != "[":
        return -1
    return i


def _matching_bracket(text: str, open_idx: int, open_ch: str, close_ch: str) -> int:
    """Returns the index of the bracket matching text[open_idx] (which
    must be open_ch), skipping over string-literal contents so a
    `]`/`}` inside a JSON string doesn't end the scan early."""
    depth: int = 0
    i: int = open_idx
    n: int = len(text)
    in_string: int = 0
    while i < n:
        ch: str = text[i]
        if in_string:
            if ch == "\\":
                i = i + 2
                continue
            if ch == "\"":
                in_string = 0
            i = i + 1
            continue
        if ch == "\"":
            in_string = 1
            i = i + 1
            continue
        if ch == open_ch:
            depth = depth + 1
        elif ch == close_ch:
            depth = depth - 1
            if depth == 0:
                return i
        i = i + 1
    return -1


def split_top_level_objects(array_text: str) -> list[str]:
    """array_text is the contents between (but not including) an array's
    `[`/`]`. Returns each top-level `{...}` object's full text (including
    its braces) as a separate string -- the elements of a glTF array are
    always objects for every array this loader reads."""
    result: list[str] = []
    i: int = 0
    n: int = len(array_text)
    while i < n:
        ch: str = array_text[i]
        if ch == "{":
            end: int = _matching_bracket(array_text, i, "{", "}")
            if end < 0:
                break
            result.append(array_text[i:end + 1])
            i = end + 1
        else:
            i = i + 1
    return result


def get_top_level_array_items(text: str, key: str) -> list[str]:
    """Top-level convenience: find `"key": [...]` and return each
    element object's text, or an empty list if the key is absent."""
    start: int = _find_key_array_start(text, key)
    if start < 0:
        return []
    end: int = _matching_bracket(text, start, "[", "]")
    if end < 0:
        return []
    inner: str = text[start + 1:end]
    return split_top_level_objects(inner)


def get_int_field(obj_text: str, key: str, default: int) -> int:
    """Scans obj_text (a single `{...}` object's text) for `"key": <int>`
    at any nesting depth reachable by plain text search -- safe here
    because every field this loader reads (index/byteOffset/byteLength/
    componentType/count/...) is a scalar, never itself an object/array
    that could contain a same-named key."""
    needle: str = "\"" + key + "\""
    idx: int = obj_text.find(needle)
    if idx < 0:
        return default
    i: int = idx + len(needle)
    n: int = len(obj_text)
    while i < n and obj_text[i] != ":":
        i = i + 1
    i = i + 1
    while i < n and (obj_text[i] == " " or obj_text[i] == "\n" or obj_text[i] == "\t" or obj_text[i] == "\r"):
        i = i + 1
    start: int = i
    if i < n and obj_text[i] == "-":
        i = i + 1
    while i < n and obj_text[i].isdigit():
        i = i + 1
    if i == start:
        return default
    return int(obj_text[start:i])


def get_str_field(obj_text: str, key: str, default: str) -> str:
    """Scans obj_text for `"key": "value"`."""
    needle: str = "\"" + key + "\""
    idx: int = obj_text.find(needle)
    if idx < 0:
        return default
    i: int = idx + len(needle)
    n: int = len(obj_text)
    while i < n and obj_text[i] != ":":
        i = i + 1
    i = i + 1
    while i < n and (obj_text[i] == " " or obj_text[i] == "\n" or obj_text[i] == "\t" or obj_text[i] == "\r"):
        i = i + 1
    if i >= n or obj_text[i] != "\"":
        return default
    i = i + 1
    start: int = i
    while i < n and obj_text[i] != "\"":
        if obj_text[i] == "\\":
            i = i + 1
        i = i + 1
    return obj_text[start:i]


def get_object_field(obj_text: str, key: str) -> str:
    """Scans obj_text for `"key": {...}` and returns the nested object's
    full text (including braces), or "" if absent -- used for e.g. a
    primitive's `"attributes": {...}` sub-object."""
    needle: str = "\"" + key + "\""
    idx: int = obj_text.find(needle)
    if idx < 0:
        return ""
    i: int = idx + len(needle)
    n: int = len(obj_text)
    while i < n and obj_text[i] != ":":
        i = i + 1
    i = i + 1
    while i < n and (obj_text[i] == " " or obj_text[i] == "\n" or obj_text[i] == "\t" or obj_text[i] == "\r"):
        i = i + 1
    if i >= n or obj_text[i] != "{":
        return ""
    end: int = _matching_bracket(obj_text, i, "{", "}")
    if end < 0:
        return ""
    return obj_text[i:end + 1]
